apiVersion: v1
kind: ServiceAccount
metadata:
  name: mesos-master
  namespace: orchestrator
  labels:
    app: mesos-master
    component: orchestration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mesos-master
  labels:
    app: mesos-master
    component: orchestration
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mesos-master
  labels:
    app: mesos-master
    component: orchestration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mesos-master
subjects:
- kind: ServiceAccount
  name: mesos-master
  namespace: orchestrator
