apiVersion: v1
kind: Service
metadata:
  name: mesos-master
  namespace: orchestrator
  labels:
    app: mesos-master
    component: orchestration
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: http
    port: 5050
    targetPort: 5050
    protocol: TCP
  selector:
    app: mesos-master
---
apiVersion: v1
kind: Service
metadata:
  name: mesos-master-lb
  namespace: orchestrator
  labels:
    app: mesos-master
    component: orchestration
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5050
    targetPort: 5050
    protocol: TCP
  selector:
    app: mesos-master
