apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: orchestrator
  labels:
    app: zookeeper
    component: coordination
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: follower
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: election
    port: 3888
    targetPort: 3888
    protocol: TCP
  - name: metrics
    port: 7070
    targetPort: 7070
    protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-client
  namespace: orchestrator
  labels:
    app: zookeeper
    component: coordination
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  selector:
    app: zookeeper
