apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: orchestrator
  namespace: orchestrator
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/component: rollout
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: orchestrator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orchestrator
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: orchestrator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: orchestrator
        image: orchestrator:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        envFrom:
        - configMapRef:
            name: orchestrator-config
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - orchestrator
              topologyKey: kubernetes.io/hostname
  strategy:
    canary:
      # Canary service name for routing canary traffic
      canaryService: orchestrator-service-canary
      # Stable service name for routing stable traffic
      stableService: orchestrator-service-stable
      # Traffic routing configuration
      trafficRouting:
        nginx:
          stableIngress: orchestrator-ingress
          additionalIngressAnnotations:
            canary-by-header: X-Canary
            canary-by-header-value: "true"
      # Canary deployment steps
      steps:
      # Step 1: Deploy canary with 10% traffic
      - setWeight: 10
      # Step 2: Pause for manual analysis (or automatic after 5 minutes)
      - pause:
          duration: 5m
      # Step 3: Run analysis to validate canary
      - analysis:
          templates:
          - templateName: success-rate
          - templateName: latency
          args:
          - name: service-name
            value: orchestrator-service-canary
      # Step 4: Increase to 25% traffic
      - setWeight: 25
      - pause:
          duration: 5m
      # Step 5: Increase to 50% traffic
      - setWeight: 50
      - pause:
          duration: 10m
      # Step 6: Run final analysis
      - analysis:
          templates:
          - templateName: success-rate
          - templateName: latency
          args:
          - name: service-name
            value: orchestrator-service-canary
      # Step 7: Increase to 75% traffic
      - setWeight: 75
      - pause:
          duration: 5m
      # Step 8: Full promotion to 100%
      - setWeight: 100
      # Maximum time for canary deployment (30 minutes)
      maxSurge: "25%"
      maxUnavailable: 0
      # Automatic rollback on analysis failure
      abortScaleDownDelaySeconds: 30
