apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - appproject.yaml
  - application.yaml
  - application-rollout.yaml
  - application-set.yaml
  - notifications.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: orchestrator
