apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orchestrator-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/component: platform
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ljluestc/orchestrator.git
    targetRevision: main
    path: helm/orchestrator
    helm:
      releaseName: orchestrator
      values: |
        global:
          namespace: orchestrator
          domain: orchestrator.local

        mesos:
          master:
            replicas: 3
            image:
              repository: mesosphere/mesos
              tag: "1.11.0"
            resources:
              requests:
                cpu: 1000m
                memory: 2Gi
              limits:
                cpu: 2000m
                memory: 4Gi
            persistence:
              enabled: true
              storageClass: standard
              size: 10Gi

          agent:
            image:
              repository: mesosphere/mesos
              tag: "1.11.0"
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 1000m
                memory: 2Gi
            hostNetwork: true
            privileged: true

        zookeeper:
          replicas: 3
          image:
            repository: zookeeper
            tag: "3.8.0"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          persistence:
            enabled: true
            storageClass: standard
            dataSize: 10Gi
            logSize: 5Gi

        marathon:
          replicas: 3
          image:
            repository: mesosphere/marathon
            tag: "v1.11.31"
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi

        monitoring:
          probe:
            image:
              repository: orchestrator-probe
              tag: latest
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
            hostNetwork: true
            privileged: true

          app:
            replicas: 3
            image:
              repository: orchestrator-app
              tag: latest
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi

          ui:
            replicas: 2
            image:
              repository: orchestrator-ui
              tag: latest
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi

        prometheus:
          enabled: true
          server:
            retention: "15d"
          alertmanager:
            enabled: true

        grafana:
          enabled: true
          adminPassword: "changeme"

  destination:
    server: https://kubernetes.default.svc
    namespace: orchestrator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
    - /spec/template/spec/containers/0/image
