apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  namespace: orchestrator
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/component: config
data:
  ORCHESTRATOR_PORT: "8080"
  ZOOKEEPER_URL: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  PROMETHEUS_PORT: "9090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: probe-agent-config
  namespace: orchestrator
  labels:
    app.kubernetes.io/name: probe-agent
    app.kubernetes.io/component: config
data:
  SERVER_URL: "http://orchestrator-service:8080"
  COLLECT_INTERVAL: "30s"
  HEARTBEAT_INTERVAL: "60s"
  LOG_LEVEL: "info"
