# Marathon Framework Deployment (Task 7)
apiVersion: v1
kind: Service
metadata:
  name: marathon
  labels:
    app: marathon
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: api
    targetPort: 8080
  selector:
    app: marathon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marathon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marathon
  template:
    metadata:
      labels:
        app: marathon
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: marathon
        image: mesosphere/marathon:v1.11.27
        ports:
        - containerPort: 8080
          name: api
        env:
        - name: MARATHON_MASTER
          value: "zk://zookeeper-0.zookeeper-headless:2181,zookeeper-1.zookeeper-headless:2181,zookeeper-2.zookeeper-headless:2181/mesos"
        - name: MARATHON_ZK
          value: "zk://zookeeper-0.zookeeper-headless:2181,zookeeper-1.zookeeper-headless:2181,zookeeper-2.zookeeper-headless:2181/marathon"
        - name: MARATHON_HTTP_PORT
          value: "8080"
        - name: MARATHON_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MARATHON_HA
          value: "true"
        - name: MARATHON_LEADER_PROXY_CONNECTION_TIMEOUT_MS
          value: "5000"
        - name: MARATHON_LEADER_PROXY_READ_TIMEOUT_MS
          value: "10000"
        - name: MARATHON_MAX_APPS
          value: "500"
        - name: MARATHON_DECLINE_OFFER_DURATION
          value: "300000"
        - name: MARATHON_TASK_LAUNCH_TIMEOUT
          value: "300000"
        - name: MARATHON_TASK_RESERVATION_TIMEOUT
          value: "20000"
        - name: MARATHON_RECONCILIATION_INITIAL_DELAY
          value: "15000"
        - name: MARATHON_RECONCILIATION_INTERVAL
          value: "600000"
        - name: MARATHON_MIN_REVIVE_OFFERS_INTERVAL
          value: "5000"
        - name: MARATHON_FRAMEWORK_NAME
          value: "marathon"
        - name: MARATHON_MESOS_ROLE
          value: "*"
        - name: MARATHON_MESOS_AUTHENTICATION_PRINCIPAL
          value: "marathon"
        - name: MARATHON_MESOS_USER
          value: "root"
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: marathon-pdb
spec:
  selector:
    matchLabels:
      app: marathon
  minAvailable: 2
