# Mesos Master Deployment with HA (Tasks 1, 13)
apiVersion: v1
kind: Service
metadata:
  name: mesos-master
  labels:
    app: mesos-master
spec:
  type: ClusterIP
  ports:
  - port: 5050
    name: api
    targetPort: 5050
  selector:
    app: mesos-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesos-master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mesos-master
  template:
    metadata:
      labels:
        app: mesos-master
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5050"
        prometheus.io/path: "/metrics"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mesos-master
              topologyKey: kubernetes.io/hostname
      containers:
      - name: mesos-master
        image: mesosphere/mesos-master:1.11.0
        ports:
        - containerPort: 5050
          name: api
        env:
        - name: MESOS_ZK
          value: "zk://zookeeper-0.zookeeper-headless:2181,zookeeper-1.zookeeper-headless:2181,zookeeper-2.zookeeper-headless:2181/mesos"
        - name: MESOS_QUORUM
          value: "2"
        - name: MESOS_CLUSTER
          value: "orchestrator-cluster"
        - name: MESOS_LOG_DIR
          value: "/var/log/mesos"
        - name: MESOS_WORK_DIR
          value: "/var/lib/mesos"
        - name: MESOS_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MESOS_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MESOS_PORT
          value: "5050"
        - name: MESOS_REGISTRY
          value: "replicated_log"
        - name: MESOS_AUTHENTICATE_FRAMEWORKS
          value: "false"
        - name: MESOS_AUTHENTICATE_HTTP_READWRITE
          value: "false"
        - name: MESOS_AUTHENTICATE_HTTP_READONLY
          value: "false"
        - name: MESOS_AUTHENTICATE_AGENTS
          value: "false"
        - name: MESOS_CREDENTIALS
          value: "/etc/mesos/credentials"
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        volumeMounts:
        - name: log-dir
          mountPath: /var/log/mesos
        - name: work-dir
          mountPath: /var/lib/mesos
        livenessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: log-dir
        emptyDir: {}
      - name: work-dir
        emptyDir: {}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mesos-master-pdb
spec:
  selector:
    matchLabels:
      app: mesos-master
  minAvailable: 2
